config/routes.rb
Rails.application.routes.draw do
  get "admin", to: "admin#index"
  controller :sessions do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def total_price
        line_items.inject(0){|sum,x| sum+=x.l_price}
    end
    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product.id)
        end
        current_item
    end
    def delete_product(product)
        del_item = line_items.find_by(product_id: product.id)
        del_item.quantity -=1
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  skip_before_action :authorize, only: [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    if @cart.id == session[:cart_id]
      @cart.destroy
      session[:cart_id] = nil
      respond_to do |format|
        format.html { redirect_to store_index_url, notice: "Your cart is currently empty" }
        format.js { }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to store_index_url, notice: "Access Denied" }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: "Invalid cart request"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
- unless cart.line_items.empty?
  %article
    - if notice
      %aside#notice_cart= notice
    %h2 Your Cart
    %table
      =render cart.line_items.order(:created_at)
      %tfoot
        %tr
          %th{:colspan => "3"} Total:
          %td.price= number_to_currency(cart.total_price,unit:"Rs ",precision: 2)
    .actions
      %table  
        %tr
          %td= button_to 'Empty cart', cart,method: :delete,remote: true,data: { confirm: 'Are you sure?' } |
          %td
          %td.checkout=button_to 'Checkout', new_order_path,method: :get if (params[:controller]!="orders" && params[:action]!="new")

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
=render @cart