config/routes.rb
Rails.application.routes.draw do
  get "admin", to: "admin#index"
  controller :sessions do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items
    has_many :orders, through: :line_items  
    before_destroy :ensure_not_referenced_by_any_line_item
  

    validates :title, :description, :image_url, presence: true
    validates :title, uniqueness: true
    validates :image_url, allow_blank: true, format: {
      with:    %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
    }
    validates :title, length: {minimum: 10}
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  
  
    private

      def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
          errors.add(:base, 'Line Items present')
          throw :abort
        end
      end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product,
          notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }

        @products = Product.all
        ActionCable.server.broadcast 'products',
          html: render_to_string('store/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
      format.atom
      format.json { render json:@product.to_json(include: :orders) }
      end
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/products/_product.html.haml
="Product Id :#{product.id}"
%li
  = image_tag(product.image_url)
  %h2=product.title
  %p
    = sanitize(product.description)
  .price
    = number_to_currency(product.price,unit:"Rs ",precision: 2)
    = button_to 'Add to Cart', line_items_path(product_id: product),remote:true
    -# - if @line_items.any?
    -#   - @line_items.each do |item|
    -#     - if item.product_id == product.id
    -#       - if item.quantity>=1
    -#         =button_to 'Remove from Cart', line_items_path(product_id: product)

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
- if notice
  %aside#notice= notice
%h1 Products
%table
  %tfoot
    %tr
      %td{:colspan => "3"}
        = link_to 'New product', new_product_path
  %tbody
    - @products.each do |product|
      %tr{class: "#{cycle('list_line_odd', 'list_line_even')}"}
        %td.image
          = image_tag(product.image_url, class: 'list_image')
        %td.description
          %h1= product.title
          %p
            = truncate(strip_tags(product.description),length: 80)
        %td.actions
          %ul
            %li= link_to 'Show', product
            %li= link_to 'Edit', edit_product_path(product)
            %li
              = link_to 'Destroy',product,method: :delete,data: { confirm: 'Are you sure?' } 

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description
%p
  %b Image url:
  = @product.image_url
%p
  %b Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path