config/routes.rb
Rails.application.routes.draw do
  get "admin", to: "admin#index"
  controller :sessions do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product ,optional: true
  belongs_to :order , optional: true
  belongs_to :cart 
  def l_price
    product.price*quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  skip_before_action :authorize, only: :create
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    p params
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)
    p @line_item
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url }
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    # @lineitem = LineItem.find(params[:id])
    if @line_item.quantity > 0
      @line_item.quantity -= 1
      @line_item.save
    end
    @line_item.destroy if @line_item.quantity == 0
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.js { @current_item = @line_item }
      format.json { render :show, status: :created, location: @line_item }
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.js { }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def line_item_params
    params.require(:line_item).permit(:product_id)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :product
    = f.text_field :product
  .field
    = f.label :cart
    = f.text_field :cart
  .actions
    = f.submit 'Save'

app/views/line_items/_line_item.html.haml
- if @current_item==line_item
  %tr.line-item-highlight
    %td= button_to '+', line_items_path(product_id: line_item.product.id),remote:true    
    %td.quantity= line_item.quantity
    %td= line_item.product.title
    %td.price= number_to_currency(line_item.l_price,unit:"Rs ",precision: 2)
    %td= button_to '-', line_item_path(line_item.id),method: :patch,remote:true
    %td= button_to '×', line_item_path(line_item.id),method: :delete,remote:true
- else
  %tr
    %td= button_to '+', line_items_path(product_id: line_item.product.id),remote:true
    %td.quantity= line_item.quantity
    %td= line_item.product.title
    %td.price= number_to_currency(line_item.l_price,unit:"Rs ",precision: 2)
    %td= button_to '-', line_item_path(line_item.id),method: :patch,remote:true
    %td= button_to '×', line_item_path(line_item.id),method: :delete,remote:true

app/views/line_items/_line_item.text.haml
=sprintf("%2d x %s",line_item.quantity,truncate(line_item.product.title, length: 50))

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %thead
    %tr
      %th Product
      %th Cart
      %th
      %th
      %th

  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product
        %td= line_item.cart
        %td= link_to 'Show', line_item
        %td= link_to 'Edit', edit_line_item_path(line_item)
        %td= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product
%p
  %b Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path