config/routes.rb
Rails.application.routes.draw do
  get "admin", to: "admin#index"
  controller :sessions do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  %div.container
    = image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf'
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "/"} Home
        %li
          %a{:href => "/questions"} Questions
        %li
          %a{:href => "/news"} News
        %li
          %a{:href => "/contact"} Contact 
        - if logged_in?
          %li= link_to "Users", users_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              =current_user.name
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: :delete
        - else
          %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pragprog Books Online Store
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 
      'data-turbolinks-track': 'reload'                
    = javascript_include_tag 'application', 
      'data-turbolinks-track': 'reload'     
  %body
    %header.main
      %nav
        = image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf'
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "/"} Home
          %li
            %a{:href => "/questions"} Questions
          %li
            %a{:href => "/news"} News
          %li
            %a{:href => "/contact"} Contact 
          - if logged_in?
            %li= link_to "Users", users_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                =current_user.name
                %b.caret
              %ul.dropdown-menu
                %li= link_to 'Orders',orders_path
                %li= link_to 'Products', products_path 
                %li.divider
                %li= button_to "Log out", logout_path , method: :delete
          - else
            %li= link_to "Log in", login_path
      %h1= @page_title

    %section.content
      %nav.side_nav
        %div#cart.carts
          - if @cart && !@cart.line_items.empty? && params[:controller]!="carts"
            =render @cart
        -# %ul
        -#   %li
        -#     %a{:href => "/"} Home
        -#   %li
        -#     %a{:href => "/questions"} Questions
        -#   %li
        -#     %a{:href => "/news"} News
        -#   %li
        -#     %a{:href => "/contact"} Contact
      %main{:class => "#{controller.controller_name}"}
        = yield
        = console
        =debug(params) 
        -# = debug(session) if Rails.env.development? 